-- atlas:pos bill[type=table] undefined
-- atlas:pos bill_item[type=table] undefined
-- atlas:pos brand[type=table] undefined
-- atlas:pos brand_category[type=table] undefined
-- atlas:pos category[type=table] undefined
-- atlas:pos currency[type=table] undefined
-- atlas:pos payment_method[type=table] undefined
-- atlas:pos product[type=table] undefined
-- atlas:pos product_alias[type=table] undefined
-- atlas:pos shop[type=table] undefined
-- atlas:pos user[type=table] undefined

CREATE TABLE `category` (`id` int UNSIGNED NOT NULL AUTO_INCREMENT, `name` varchar(100) COLLATE "utf8mb4_bin" NOT NULL, `description` tinytext NULL, `created_at` timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0), `updated_at` timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0) ON UPDATE CURRENT_TIMESTAMP(0), `deleted_at` timestamp(0) NULL, UNIQUE INDEX `idx_category_name` (`name`), PRIMARY KEY (`id`)) ENGINE=InnoDB;
CREATE TABLE `brand_category` (`id_brand` int UNSIGNED NOT NULL, `id_category` int UNSIGNED NOT NULL, `created_at` timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0), `updated_at` timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0) ON UPDATE CURRENT_TIMESTAMP(0), `deleted_at` timestamp(0) NULL, PRIMARY KEY (`id_brand`, `id_category`)) ENGINE=InnoDB;
CREATE TABLE `brand` (`id` int UNSIGNED NOT NULL AUTO_INCREMENT, `name` varchar(50) COLLATE "utf8mb4_bin" NOT NULL, `created_at` timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0), `updated_at` timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0) ON UPDATE CURRENT_TIMESTAMP(0), `deleted_at` timestamp(0) NULL, UNIQUE INDEX `idx_brand_name` (`name`), PRIMARY KEY (`id`)) ENGINE=InnoDB;
CREATE TABLE `product` (`id` int UNSIGNED NOT NULL AUTO_INCREMENT, `id_brand` int UNSIGNED NOT NULL, `id_category` int UNSIGNED NOT NULL, `name` varchar(255) COLLATE "utf8mb4_bin" NOT NULL, `description` tinytext NULL, `created_at` timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0), `updated_at` timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0) ON UPDATE CURRENT_TIMESTAMP(0), `deleted_at` timestamp(0) NULL, INDEX `idx_product_id_category` (`id_category`), INDEX `idx_product_id_brand` (`id_brand`), UNIQUE INDEX `idx_product_name` (`name`), PRIMARY KEY (`id`)) ENGINE=InnoDB;
CREATE TABLE `bill_item` (`id` int UNSIGNED NOT NULL AUTO_INCREMENT, `id_bill` int UNSIGNED NOT NULL, `id_product` int UNSIGNED NOT NULL, `quantity` int UNSIGNED NOT NULL, `content_value` decimal(10,3) UNSIGNED NULL, `net_price` decimal(10,2) UNSIGNED NOT NULL, `net_unit` enum ('g', 'kg', 'l', 'ml', 'u') NOT NULL, `created_at` timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0), `updated_at` timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0) ON UPDATE CURRENT_TIMESTAMP(0), `deleted_at` timestamp(0) NULL, INDEX `idx_bill_item_product_price` (`id_product`, `net_price`, `id_bill`), UNIQUE INDEX `uq_bill_item` (`id_bill`, `id_product`), PRIMARY KEY (`id`)) ENGINE=InnoDB;
CREATE TABLE `shop` (`id` int UNSIGNED NOT NULL AUTO_INCREMENT, `name` varchar(255) CHARACTER SET "utf8mb4" COLLATE "utf8mb4_bin" NOT NULL, `description` tinytext NULL, `latitude` double(9,6) NULL, `longitude` double(9,6) NULL, `created_at` timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0), `updated_at` timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0) ON UPDATE CURRENT_TIMESTAMP(0), `deleted_at` timestamp(0) NULL, INDEX `idx_shop_location` (`latitude`, `longitude`), UNIQUE INDEX `idx_shop_name` (`name`), PRIMARY KEY (`id`)) ENGINE=InnoDB;
CREATE TABLE `currency` (`id` int UNSIGNED NOT NULL AUTO_INCREMENT, `code` varchar(10) NOT NULL, `name` varchar(100) NOT NULL, `symbol` varchar(10) NULL, `created_at` timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0), `updated_at` timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0) ON UPDATE CURRENT_TIMESTAMP(0), `deleted_at` timestamp(0) NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB;
CREATE TABLE `payment_method` (`id` int UNSIGNED NOT NULL AUTO_INCREMENT, `uuid` binary(16) NULL, `name` varchar(150) NOT NULL, `description` tinytext NULL, `created_at` timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0), `updated_at` timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0) ON UPDATE CURRENT_TIMESTAMP(0), `deleted_at` timestamp(0) NULL, UNIQUE INDEX `IDX_8aa6ca0f30ddb213477a2bb577` (`uuid`), UNIQUE INDEX `IDX_6101666760258a840e115e1bb1` (`name`), PRIMARY KEY (`id`)) ENGINE=InnoDB;
CREATE TABLE `bill` (`id` int UNSIGNED NOT NULL AUTO_INCREMENT, `id_shop` int UNSIGNED NOT NULL, `id_currency` int UNSIGNED NOT NULL, `id_payment_method` int UNSIGNED NOT NULL, `id_user` int UNSIGNED NOT NULL, `sub_total` decimal(10,2) UNSIGNED NOT NULL, `discount` decimal(10,2) UNSIGNED NULL DEFAULT '0.00', `total` decimal(10,2) UNSIGNED NOT NULL, `id_user_owner` int UNSIGNED NOT NULL, `purchased_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP(0), `receipt_number` varchar(150) NULL, `created_at` timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0), `updated_at` timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0) ON UPDATE CURRENT_TIMESTAMP(0), `deleted_at` timestamp(0) NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB;
CREATE TABLE `user` (`id` int UNSIGNED NOT NULL AUTO_INCREMENT, `name` varchar(100) NOT NULL, `surname` varchar(100) NULL, `email` varchar(100) NOT NULL, `username` varchar(100) COLLATE "utf8mb4_bin" NOT NULL, `password` varchar(255) COLLATE "utf8mb4_bin" NOT NULL, `role` enum ('admin', 'user', 'guest') NOT NULL DEFAULT 'guest', `created_at` timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0), `updated_at` timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0) ON UPDATE CURRENT_TIMESTAMP(0), `deleted_at` timestamp(0) NULL, UNIQUE INDEX `idx_user_username` (`username`), UNIQUE INDEX `idx_user_email` (`email`), PRIMARY KEY (`id`)) ENGINE=InnoDB;
CREATE TABLE `product_alias` (`id` int UNSIGNED NOT NULL AUTO_INCREMENT, `id_product` int UNSIGNED NOT NULL, `id_shop` int UNSIGNED NOT NULL, `alias_name` varchar(255) NOT NULL, UNIQUE INDEX `uq_shop_alias` (`id_shop`, `alias_name`), PRIMARY KEY (`id`)) ENGINE=InnoDB;
ALTER TABLE `brand_category` ADD CONSTRAINT `FK_3182397f713e52ec980960d34c7` FOREIGN KEY (`id_brand`) REFERENCES `brand`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE `brand_category` ADD CONSTRAINT `FK_1e9aee9ce30ccc28da157f34b40` FOREIGN KEY (`id_category`) REFERENCES `category`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE `product` ADD CONSTRAINT `FK_31d111371fb2976c7a8e124fb23` FOREIGN KEY (`id_brand`) REFERENCES `brand`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;
ALTER TABLE `product` ADD CONSTRAINT `FK_728568cd9497499e160be34dddd` FOREIGN KEY (`id_category`) REFERENCES `category`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;
ALTER TABLE `product` ADD CONSTRAINT `FK_3e0e14707fab21dc0f205b971cc` FOREIGN KEY (`id_brand`, `id_category`) REFERENCES `brand_category`(`id_brand`,`id_category`) ON DELETE RESTRICT ON UPDATE RESTRICT;
ALTER TABLE `bill_item` ADD CONSTRAINT `FK_99d84132c2b10635533d58c9a77` FOREIGN KEY (`id_product`) REFERENCES `product`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;
ALTER TABLE `bill_item` ADD CONSTRAINT `FK_5bb406e0e449fb2663af14e207a` FOREIGN KEY (`id_bill`) REFERENCES `bill`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `bill` ADD CONSTRAINT `FK_add5b4308af421093b156a5afe8` FOREIGN KEY (`id_shop`) REFERENCES `shop`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE `bill` ADD CONSTRAINT `FK_a6eea9ed9093e3f38e9a4f0ed27` FOREIGN KEY (`id_currency`) REFERENCES `currency`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE `bill` ADD CONSTRAINT `FK_9c67ad9818955c307ef0445cf30` FOREIGN KEY (`id_payment_method`) REFERENCES `payment_method`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE `bill` ADD CONSTRAINT `FK_87e0b890c4ccf72cb88ec640143` FOREIGN KEY (`id_user_owner`) REFERENCES `user`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE `bill` ADD CONSTRAINT `FK_6498532ac094ed754c680d064e1` FOREIGN KEY (`id_user`) REFERENCES `user`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE `product_alias` ADD CONSTRAINT `FK_62894c349fb1d65793f545dfbcb` FOREIGN KEY (`id_product`) REFERENCES `product`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE `product_alias` ADD CONSTRAINT `FK_d8fda1ebcff1a571f0c2601d1ed` FOREIGN KEY (`id_shop`) REFERENCES `shop`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
